//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProjectManager.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Calendar
    {
        public System.Guid CalendarGUID { get; set; }
        public Nullable<System.Guid> EmployeeGUID { get; set; }
        public Nullable<System.DateTime> StartTime { get; set; }
        public Nullable<System.DateTime> EndTime { get; set; }
        public string EventTitle { get; set; }
        public Nullable<int> Opacity { get; set; }
        public Nullable<int> Red { get; set; }
        public Nullable<int> Green { get; set; }
        public Nullable<int> Blue { get; set; }
    
        public virtual Employee Employee { get; set; }
    }
}
