//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProjectManager.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CostPool
    {
        public System.Guid PoolGUID { get; set; }
        public int PoolID { get; set; }
        public string PoolName { get; set; }
        public Nullable<decimal> WagePerHour { get; set; }
        public Nullable<decimal> RentalPerMonth { get; set; }
        public Nullable<decimal> UtilityPerMonth { get; set; }
        public Nullable<decimal> OtherManagementCosts { get; set; }
        public string InterestExpense { get; set; }
        public Nullable<decimal> RiskPreparationCost { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public Nullable<System.DateTime> ModifiedDate { get; set; }
    }
}
