//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProjectManager.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CostEstimateSheet
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public CostEstimateSheet()
        {
            this.CostEstimateSheetDetail = new HashSet<CostEstimateSheetDetail>();
        }
    
        public System.Guid SheetGUID { get; set; }
        public int SheetID { get; set; }
        public string SheetName { get; set; }
        public Nullable<System.Guid> ProjectGUID { get; set; }
        public string Description { get; set; }
        public Nullable<decimal> Rental { get; set; }
        public Nullable<decimal> Utility { get; set; }
        public Nullable<decimal> OtherManagement { get; set; }
        public Nullable<decimal> Interest { get; set; }
        public Nullable<decimal> RiskPreparation { get; set; }
        public Nullable<System.DateTime> CreateDate { get; set; }
        public Nullable<System.DateTime> ModifiedDate { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CostEstimateSheetDetail> CostEstimateSheetDetail { get; set; }
    }
}
