//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProjectManager.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Dashboard
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Dashboard()
        {
            this.WidgetDetail = new HashSet<WidgetDetail>();
        }
    
        public System.Guid DashBoardGUID { get; set; }
        public int SequenceID { get; set; }
        public Nullable<int> PositionTop { get; set; }
        public Nullable<int> PositionLeft { get; set; }
        public Nullable<int> WidgetWidth { get; set; }
        public Nullable<int> WidgetHeight { get; set; }
        public Nullable<System.Guid> EmployeeGUID { get; set; }
    
        public virtual Employee Employee { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<WidgetDetail> WidgetDetail { get; set; }
    }
}
