//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProjectManager.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class DocumentModified
    {
        public System.Guid DocumentGUID { get; set; }
        public System.Guid ModifiedGUID { get; set; }
        public Nullable<int> Version { get; set; }
        public Nullable<System.DateTime> ModifiedDate { get; set; }
        public Nullable<System.Guid> ModifiedEmpGUID { get; set; }
        public Nullable<bool> IsChecked { get; set; }
        public string FileName { get; set; }
    
        public virtual Document Document { get; set; }
        public virtual Employee Employee { get; set; }
    }
}
