//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProjectManager.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Document
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Document()
        {
            this.DocumentModified = new HashSet<DocumentModified>();
        }
    
        public int DocumentID { get; set; }
        public System.Guid DocumentGUID { get; set; }
        public Nullable<int> DocumentCategory { get; set; }
        public Nullable<System.Guid> ProjectGUID { get; set; }
        public Nullable<System.Guid> TaskGUID { get; set; }
        public string DocumentName { get; set; }
        public Nullable<System.DateTime> CreateDate { get; set; }
        public Nullable<System.Guid> CreateEmpGUID { get; set; }
    
        public virtual DocumentCategory DocumentCategory1 { get; set; }
        public virtual Employee Employee { get; set; }
        public virtual Project Project { get; set; }
        public virtual Tasks Tasks { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DocumentModified> DocumentModified { get; set; }
    }
}
