//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProjectManager.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ProjectMembers
    {
        public System.Guid EmployeeGUID { get; set; }
        public System.Guid ProjectGUID { get; set; }
        public Nullable<byte> PMscore { get; set; }
        public Nullable<byte> Selfscore { get; set; }
        public Nullable<System.DateTime> InvideDate { get; set; }
        public Nullable<bool> IsRead { get; set; }
        public Nullable<System.DateTime> PMScoreDate { get; set; }
        public Nullable<System.DateTime> SelfScoreDate { get; set; }
        public string Reviewer { get; set; }
    
        public virtual Employee Employee { get; set; }
        public virtual Project Project { get; set; }
    }
}
