//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProjectManager.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Widgets
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Widgets()
        {
            this.Dashboard = new HashSet<Dashboard>();
        }
    
        public System.Guid WidgetGUID { get; set; }
        public string WidgetName { get; set; }
        public string WidgetDesc { get; set; }
        public byte[] WidgetImage { get; set; }
        public Nullable<System.Guid> WidgetDetailGUID { get; set; }
        public Nullable<bool> AdminPermit { get; set; }
        public Nullable<bool> DirectorPermit { get; set; }
        public Nullable<bool> MinisterPermit { get; set; }
        public Nullable<bool> ProjectManagerPermit { get; set; }
        public Nullable<bool> ProgrammerPermit { get; set; }
        public string ActionResultName { get; set; }
    
        public virtual WidgetDetail WidgetDetail { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Dashboard> Dashboard { get; set; }
    }
}
