//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProjectManager.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class WidgetDetail
    {
        public System.Guid WidgetGUID { get; set; }
        public string WidgetName { get; set; }
        public string WidgetDesc { get; set; }
        public string WidgetImagePath { get; set; }
        public Nullable<System.Guid> DashBoardGUID { get; set; }
    
        public virtual Dashboard Dashboard { get; set; }
    }
}
